### ISSUE TITLE
UITextField does not respond reliable to touch events

### ISSUE THREAD

**Issue by planetexpress69** [miscavage/Popup#1]
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {

    return NO;
}

seems to cure that.

**Comment by miscavage** [comment]
Got it, thanks. Just pushed new commit.
