### ISSUE TITLE
popup disappear right after it shows up when it is being called in a UIAlerView delegate method clickedButtonAtIndex

### ISSUE THREAD

**Issue by daarkfish** [miscavage/Popup#4]
I have a button in a uitableviewcell which will show an alertview and when pressed on OK button it will call its delegate method to show the popup 

The popup shows up successfully but disappear right after it shows up.

**Comment by miscavage** [comment]
Hi daarkfish. I've managed to replicate this bug and am working on a fix right now. Will let you know when a I push a fix!

**Comment by miscavage** [comment]
Hey daarkfish, after messing with it a little bit I've come to the conclusion that UIAlertView's take time to dismiss the actual view and along with that I believe they destroy the UIWindow as well in alertView:clickedButtonAtIndex:

I've come up with a workaround :
![popup_workaround](https://cloud.githubusercontent.com/assets/4645056/8711490/6db54c5e-2b20-11e5-9212-c1810acd2417.png)

Basically the smallest amount of time it takes for a UIAlertView to dismiss is 0.40829 seconds. So after that time period you want to show Popup.
