### ISSUE TITLE
Popup not showing in some viewcontrollers but shows up on others

### ISSUE THREAD

**Issue by xarlotie** [miscavage/Popup#5]
Hi!

What could be the reason why the popup doesn't show in one viewcontroller but does not in another viewcontroller? I can't find the cause of this issue. Thanks!

**Comment by miscavage** [comment]
Hey xarlotie,

An issue could be is if you have any subviews in your UIWindow or something else that seemed to cause Popup not to show is if you have a tableview or scrollview on the view?
Could you give me a little bit more info on the viewcontroller where it's not working at?

**Comment by xarlotie** [comment]
I found the real culprit. I tried it on iOS 7.1 and it worked. It is not working on iOS 8.

**Comment by miscavage** [comment]
That is very odd, it should definitely work on 8.1 and 8.4. 
Let me know if you have any other trouble!

**Comment by miscavage** [comment]
Please update to latest commit and let me know if you are still experiencing issues,
