### ISSUE TITLE
No visible @interface for 'Popup' declares the selector 'initWithTitle:subTitle:textField Placeholder:cancelTitle:success Title:'

### ISSUE THREAD

**Issue by badalpub1991** [miscavage/Popup#6]
When i am using   `textFieldPlaceholders` without using block then it will give such type of error.

Error : - No visible @interface for 'Popup' declares the selector 'initWithTitle:subTitle:textField Placeholder:cancelTitle:success Title:'

Here i have pasted my code for popup. 

    -(void)presentpopup
    {
      [self toggleLeftSideMenuCompletion:nil];

        Popup *popup = [[Popup alloc] initWithTitle:@"demo"
                                       subTitle:@"Please enter the Details"
                          textFieldPlaceholders:@[@"Name",@"Website",@"RSS Feed URL"]
                                    cancelTitle:@"Cancel"
                                   successTitle:@"Submit"
         / /                                    cancelBlock:^{
         //                                        nil;
        //                                        //Custom code after cancel button was pressed
       //                                    } successBlock:^{
      ////                                        MainViewController *mainviewcontroller=[[MainViewController alloc]init];
       ////                                        mainviewcontroller.url=_URL1;
       ////                                        [mainviewcontroller CallForWebService];
         //                                       // temp = [te stringByAppendingFormat:@"%@", [RomanosBasicos objectAtIndex:i]];
       //                                        nil;
       //                                        //Custom code after success button was pressed
       //                                        
      //                                    }];
    
                    ];
    
          [popup setDelegate:self];
         //[popup setBackgroundColor:[UIColor colorWithPatternImage:[UIImage imageNamed:@"Default-736h@3x.png"]]];
    
         [popup setBackgroundColor:[UIColor whiteColor]];
         [popup setBorderColor:[UIColor colorWithRed:98.0f/255.0f green:42.0f/255.0f blue:101.0f/255.0f alpha:1]];
        [popup setTitleColor:[UIColor colorWithRed:98.0f/255.0f green:42.0f/255.0f blue:101.0f/255.0f alpha:1]];
         [popup setSubTitleColor:[UIColor colorWithRed:98.0f/255.0f green:42.0f/255.0f blue:101.0f/255.0f alpha:1]];    [popup setCancelBtnColor:[UIColor colorWithRed:98.0f/255.0f green:42.0f/255.0f blue:101.0f/255.0f alpha:1]];
         [popup setSuccessBtnColor:[UIColor colorWithRed:98.0f/255.0f green:42.0f/255.0f blue:101.0f/255.0f alpha:1]];
       [popup setRoundedCorners:YES];
       [popup setIncomingTransition:PopupIncomingTransitionTypeGhostAppear];
       [popup setOutgoingTransition:PopupOutgoingTransitionTypeGhostDisappear];
       [popup setSwipeToDismiss:YES];
       [popup setBackgroundBlurType:PopupBackGroundBlurTypeLight];
       [popup showPopup];
      }

![screen shot 2015-10-12 at 10 36 28 am](https://cloud.githubusercontent.com/assets/11573422/10421796/3ad54a1c-70cd-11e5-9516-97095d05716e.png)

**Comment by miscavage** [comment]
Hi badalpub1991, 

This error is because there is no function created for:
"initWithTitle: subTitle: textFieldPlaceholders: cancelTitle: successTitle:"

It needs to be:
"initWithTitle: subTitle: textFieldPlaceholders: cancelTitle: successTitle: cancelBlock: successBlock:"
In other words, you need the blocks to be in there for it to work. Even if you just have them empty.

You can also create your own function without Blocks and including Textfields within Popup.h and Popup.m, I'll outline exactly how you can do that below:

In Popup.h put this:
- (instancetype)initWithTitle:(NSString *)title
                     subTitle:(NSString *)subTitle
        textFieldPlaceholders:(NSArray *)textFieldPlaceholderArray
                  cancelTitle:(NSString *)cancelTitle
                 successTitle:(NSString *)successTitle;

Then in Popup.m put this:
- (instancetype)initWithTitle:(NSString *)title
                     subTitle:(NSString *)subTitle
        textFieldPlaceholders:(NSArray *)textFieldPlaceholderArray
                  cancelTitle:(NSString *)cancelTitle
                 successTitle:(NSString *)successTitle {
    
    if ([super init]) {
        pTitle = title;
        pSubTitle = subTitle;
        pTextFieldPlaceholderArray = textFieldPlaceholderArray;
        pCancelTitle = cancelTitle;
        pSuccessTitle = successTitle;
        
        [self formulateEverything];
    }
    
    return self;
}

**Comment by badalpub1991** [comment]
Hi  miscavage,
   Thanks for replay. means after implement this can i use it without block ?

        In Popup.h put this:

      (instancetype)initWithTitle:(NSString *)title subTitle:(NSString *)subTitle textFieldPlaceholders:(NSArray *)textFieldPlaceholderArray cancelTitle:(NSString *)cancelTitle successTitle:(NSString *)successTitle;

Then in Popup.m put this:

     (instancetype)initWithTitle:(NSString *)title
     subTitle:(NSString *)subTitle
     textFieldPlaceholders:(NSArray *)textFieldPlaceholderArray
     cancelTitle:(NSString *)cancelTitle
     successTitle:(NSString *)successTitle {

     if ([super init]) {
     pTitle = title;
     pSubTitle = subTitle;
     pTextFieldPlaceholderArray = textFieldPlaceholderArray;
     pCancelTitle = cancelTitle;
     pSuccessTitle = successTitle;

     [self formulateEverything];

     }
      return self;
    }

Because with calling my method (callforwebservice) in block i am getting nil tableview. (means when i call [self.tableview reloaddata] it will not go to datasource method)I have checked all the things. tableview configuration is correct. so, i will try it with button's delegate method.
Here is link how i used this popup.

http://paste.ubuntu.com/12770690/

I hope i am using it in correct-way thanks. 

and one more thing, thanks a lot for this popup. it is awsome and very easy and user-friendly to implement.

**Comment by badalpub1991** [comment]
and one more thing is it possible to set validation on text field of popup ?

**Comment by miscavage** [comment]
Hi, for your first problem, try putting the CallForWebService in the delegate method: 

- (void)popupPressButton:(Popup *)popup buttonType:(PopupButtonType)buttonType {
   [self CallForWebService];
}

Instead of in the block method:

successBlock:^{
     [self CallForWebService];
     //Custom code after success button was pressed                                        
}

**Comment by miscavage** [comment]
For the textfields dismissing when there's no text you can do a few things:
1: If there's no text in the textfield, you can show another popup.
2: Go into Popup.m and make sure that all text fields have text in them before dismissing them. This requires a little bit more logic and code to work.

**Comment by badalpub1991** [comment]
this method is not executed while i am using block .
-(void)popupPressButton:(Popup *)popup buttonType:(PopupButtonType)buttonType

and if i am not using block then i ma not able to add text field in popup.

**Comment by miscavage** [comment]
Just fixed this issue. See latest commit!
