### ISSUE TITLE
How to show default Text ?

### ISSUE THREAD

**Issue by abhisheknik23** [miscavage/Popup#8]
In my app i am using popup for update user profile and for that i need to by default show the user last Text in to textfield. How can i do that?

**Comment by badalpub1991** [comment]
you need to use  below method in this way.
          
         - (void)dictionary:(NSMutableDictionary *)dictionary forpopup:(Popup *)popup stringsFromTextFields:(NSArray *)stringArray {
    
nsstring *Name;
nsstring *Websitename;
nsstring *Feedlink;
    
    Name = [stringArray objectAtIndex:0];
   NSLog(@"Name ---> %@",Name);

      WebsiteName = [stringArray objectAtIndex:1];
       NSLog(@"Websitename ---> %@",Websitename);

      Feedlink = [stringArray objectAtIndex:2];

       NSLog(@"Feedlink ---> %@",_Feedlink);
 
}
You will get user's input text as string and then use it where you want.

**Comment by miscavage** [comment]
Hi abhisheknik23, 

Right now you can only set the placeholders of the textfields. You can't actually set the text within the textfields.

**Comment by miscavage** [comment]
See latest commit for this functionality!
